server:
  port: 8888
spring:
  application:
    name: api-gateway-server
    
  cloud:
    gateway:
      routes:
      - id: student-ms
        uri:
          lb://student-ms
        predicates:
        - Path=/api/**
        
        
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
          cors-configurations: 
            '[/**]':
              allowed-origins: "*"
              allowed-methods: "*"
              allowed-headers: "*"
        
        